import { Toaster } from "sonner";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";

const font = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className}  antialiased`}>
        <TRPCReactProvider>
          {children}
          <Toaster position="top-right" closeButton />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
